### ISSUE TITLE
Provide the knime workflow for import/conversion of images from other systems

### ISSUE THREAD

**Issue by LauLauThom** [sscholz-UFZ/FishInspector#1]
Hello and thank you for the tool, I successfully installed the software on my pc and open some images.
I don't use a capillary mounting so I was looking for the knime workflow to pre-process my images.
Is it on the GitHub too ?

**Comment by LauLauThom** [comment]
I found it on [Dryad](https://datadryad.org/resource/doi:10.5061/dryad.gv144d5), but I think it would be nice to add them to the GitHub repo too

**Comment by eteixido** [comment]
Hello, the Knime workflows are here: https://github.com/eteixido/Knime-workflows-FishInspector. 
I would add a note in the readme file. Thanks a lot !
